server:
  port: 8090
spring:
  application:
    name: "loans"
  datasource:
    url: "jdbc:h2:mem:testdb"
    driverClassName: org.h2.Driver
    username: "sa"
    password: ''
  jpa:
    ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        enabled: true