server:
  port: 8080
spring:
  application:
    name: "accounts"
  datasource:
    username: sa
    password: ''
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  hibernate:
    ddl-auto: update
  show-sql: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#    connection-timeout: 10s
  cloud:
    stream:
      bindings:
        sendCommunication-out-0:
          destination: send-communication
        updateCommunicationStatus-in-0:
          destination: communication-sent
          group: ${spring.application.name}
      kafka:
        binder:
          brokers:
            - localhost:9092
